### ISSUE TITLE
请问这个模型在预测的时候能否使用多个cpu?

### ISSUE THREAD

**Issue by liandanjia** [paddleseg/ai-seg-model#2]
RT

**Comment by andy-zhangtao** [comment]
默认使用单核CPU。 预测时可以试试添加 exporte CPU_NUM=N 使用多核CPU

**Comment by liandanjia** [comment]
这个我试了，好像不起作用。我看到utils.py中的get_environ_info()函数能读CPU_NUM的数值，但是没人调用get_environ_info()啊。

**Comment by andy-zhangtao** [comment]
你看一下容器启动时，物理节点给它分配了多少核的CPU。 是单核还是多核？ paddlepaddle执行时，框架代码会检测CPU_NUM这个变量。

**Comment by liandanjia** [comment]
百度的人说不建议用cpu加速，我试试用gpu来搞吧。有问题再请教你啊。
