### ISSUE TITLE
请教一个问题：怎么开启gpu推理？

### ISSUE THREAD

**Issue by liandanjia** [paddleseg/ai-seg-model#3]
你好，cpu推理还是太慢了。想改成gpu推理的话，是不是应该往docker image里装cuda、cudnn这些？还有别的需要做的吗？
谢谢！

**Comment by andy-zhangtao** [comment]
这个docker版本，我没有显示安装gpu引擎。 你可以尝试在Dockerfile使用nvidia-docker作为base image，创建container时使用 - - gpus，允许容器使用gpu。  
这样看一下有没有效果

**Comment by liandanjia** [comment]
收到，刚才试了一下自己创建docker image.
我从这里：https://github.com/paddleseg/ai-seg-model/releases/tag/v0.2.0 下载了你的模型和代码，然后运行docker build，然而我创建的image推理一张图用了48秒。。。是myModel有问题吗？

**Comment by andy-zhangtao** [comment]
原图是多大的？ 我试过最大1M的原图，Mac pro 4C 16G，容器资源2C4G 推测时间3s左右。  48秒太长，不正常。

**Comment by liandanjia** [comment]
原图也就50kb，请问怎么debug它呢？
我在你的Dockerfile中添加了COPY myModel /app/myModel，不然image中没有模型。

**Comment by liandanjia** [comment]
像flask框架的问题，用curl发post会卡住一段时间，但是用浏览器访问127.0.0.1/upload又挺快，会出“Method Not Allowed”页面。

**Comment by andy-zhangtao** [comment]
简单的定位方式是，在python调用模型预测的代码之前，添加一行debug日志。 通过判断日志输出的时间大致定位一下是Flask的问题还是模型执行的问题。 
https://github.com/paddleseg/ai-seg-model/blob/b5fe08c96ebc6fdb13471eff041c49fcd6ff0131/seg.py#L187
可以在这里输出debug日志

**Comment by andy-zhangtao** [comment]
> 像flask框架的问题，用curl发post会卡住一段时间，但是用浏览器访问127.0.0.1/upload又挺快，会出“Method Not Allowed”页面。

浏览器发送的是GET请求，所以Flask会返回Method Not Allowed

**Comment by liandanjia** [comment]
不太会改container里的文件。。。在container外面改好copy进去，又不生效，请问有除了重新创建image之外的简单方法吗？我微信号是liandanjia，可以加我一下在微信上聊。。

**Comment by andy-zhangtao** [comment]
> 不太会改container里的文件。。。在container外面改好copy进去，又不生效，请问有除了重新创建image之外的简单方法吗？我微信号是liandanjia，可以加我一下在微信上聊。。

:smile:  这个问题很容易解决。  创建容器的时候通过 --entrypoint bash 修改默认行为， 然后按照你的逻辑修改代码逻辑。 修改完以后，在/app 目录执行 python3 app.py 就可以执行新代码了。

**Comment by liandanjia** [comment]
在docker run -it ......这条命令后面跟上--entrypoint bash吗？不行啊。。仍然会监听80端口，得不到shell。

**Comment by andy-zhangtao** [comment]
docker run -it --entrypoint bash -p 80:80 xxxxxxxxxx

**Comment by liandanjia** [comment]
谢谢兄弟！刚才测了一下，在187行添加print，运行app.py，然后提交图片，发现print能立刻执行，证明应该是模型的问题。

**Comment by liandanjia** [comment]
应该是model.predict()的问题。

**Comment by liandanjia** [comment]
原因找到了，应该是https://github.com/paddleseg/ai-seg-model/releases/tag/v0.2.0的模型或者其中的deploy.yaml文件有问题，替换成你做好的image中的模型就没问题了。

**Comment by andy-zhangtao** [comment]
> 原因找到了，应该是[https://github.com/paddleseg/ai-seg-model/releases/tag/v0.2.0的模型或者其中的deploy.yaml文件有问题，替换成你做好的image中的模型就没问题了。](https://github.com/paddleseg/ai-seg-model/releases/tag/v0.2.0%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%88%96%E8%80%85%E5%85%B6%E4%B8%AD%E7%9A%84deploy.yaml%E6%96%87%E4%BB%B6%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E6%9B%BF%E6%8D%A2%E6%88%90%E4%BD%A0%E5%81%9A%E5%A5%BD%E7%9A%84image%E4%B8%AD%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%B0%B1%E6%B2%A1%E9%97%AE%E9%A2%98%E4%BA%86%E3%80%82)

Nice！  deploy.yaml 里面的参数需要和模型里面的参数匹配使用。 这个文件是训练时使用的参数，每次训练如果修改了参数，那么这个文件就会发生变化。

**Comment by liandanjia** [comment]
明白，我打算让模型支持gpu推理，有问题再请教你啊。多谢了！
