### ISSUE TITLE
为啥用paddleSeg.Predictor()加载模型，而不是models.load_model()？

### ISSUE THREAD

**Issue by liandanjia** [paddleseg/ai-seg-model#4]
有什么考虑吗？

**Comment by liandanjia** [comment]
@andy-zhangtao 
你好，请问deploy.yaml怎么生成？我的模型导出后只有个model.yml，model.yml的内容和你的deploy.yaml的内容非常不一样。用我的模型配合你的deploy.yaml倒是能运行，但是出来的结果是空的。感觉你的导出方法和我的不一样，求指导啊。

**Comment by andy-zhangtao** [comment]
没特别的考虑，我是参考的官方文档写的代码。 😄

**Comment by andy-zhangtao** [comment]
> @andy-zhangtao
> 你好，请问deploy.yaml怎么生成？我的模型导出后只有个model.yml，model.yml的内容和你的deploy.yaml的内容非常不一样。用我的模型配合你的deploy.yaml倒是能运行，但是出来的结果是空的。感觉你的导出方法和我的不一样，求指导啊。

deploy.yaml是在训练前准备的参数，准备预测时，先加载模型，然后再使用这份文件获取模型参数。最后调用API获取预测结果。

**Comment by liandanjia** [comment]
明白了，多谢！
